version: "3.9"

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb+srv://kathirvelvlr108_db_user:Kathirvelkathir1@@cluster0.r5feew2.mongodb.net/user-service
    depends_on:
      - mongo

  audit-service:
    build: ./audit-service
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb+srv://kathirvelvlr108_db_user:Kathirvelkathir1@@cluster0.r5feew2.mongodb.net/auditdb
    depends_on:
      - mongo

  frontend:
    build: ./frontEnd
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - audit-service

  mongo:
    image: mongo
    ports:
      - "27017:27017"